// Code generated by tools/fsroutes. DO NOT EDIT.
// Source of truth is the directory tree under client/pages.

package pages

import (
	"github.com/mirairoad/howl-go/core/router"
	p0 "github.com/mirairoad/howl-go/examples/toy_app/client/pages/about"
	p1 "github.com/mirairoad/howl-go/examples/toy_app/client/pages/blog"
	p2 "github.com/mirairoad/howl-go/examples/toy_app/client/pages/dashboard"
	p3 "github.com/mirairoad/howl-go/examples/toy_app/client/pages/dashboard/metrics"
	p4 "github.com/mirairoad/howl-go/examples/toy_app/client/pages/dashboard/settings"
	p5 "github.com/mirairoad/howl-go/examples/toy_app/client/pages/todos"
)

// FsClientRoutes is the route table derived from the page tree.
func FsClientRoutes() []router.Route {
	return []router.Route{
		{Pattern: "/", Label: "Home", Page: Page, Head: nil, Mount: nil, Unmount: nil, Layouts: nil, Client: false},
		{Pattern: "/about", Label: "About", Page: p0.Page, Head: nil, Mount: nil, Unmount: nil, Layouts: nil, Client: false},
		{Pattern: "/blog", Label: "Blog", Page: p1.Page, Head: nil, Mount: nil, Unmount: nil, Layouts: nil, Client: false},
		{Pattern: "/dashboard", Label: "Dashboard", Page: p2.Page, Head: nil, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{p2.Layout}, Client: true},
		{Pattern: "/dashboard/metrics", Label: "Metrics", Page: p3.Page, Head: p3.Head, Mount: p3.Mount, Unmount: nil, Layouts: []router.Wrapper{p2.Layout}, Client: true},
		{Pattern: "/dashboard/settings", Label: "Settings", Page: p4.Page, Head: nil, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{p2.Layout}, Client: true},
		{Pattern: "/todos", Label: "Todos", Page: p5.Page, Head: nil, Mount: p5.Mount, Unmount: p5.Unmount, Layouts: nil, Client: false},
		{Pattern: "/blog/{article_id}", Label: "Article_id", Page: p1.Article, Head: nil, Mount: nil, Unmount: nil, Layouts: nil, Client: false},
	}
}
