package main

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"sort"
	"strings"
	"unicode"
)

// renderTable writes the registerable list. api.At carries the derived path, so
// the endpoint file itself never repeats its own URL.
func renderTable(endpoints []endpoint, pkg, dir, apiPkg string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by core/cmd/fsapis. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source of truth is the directory tree under %s.\n\n", dir)
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	imports := map[string]string{}
	for _, e := range endpoints {
		if e.Alias != "" {
			imports[e.Alias] = e.Import
		}
	}
	fmt.Fprintf(&b, "import (\n\t%q\n", apiPkg)
	for _, alias := range sortedKeys(imports) {
		fmt.Fprintf(&b, "\t%s %q\n", alias, imports[alias])
	}
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(&b, "// FsApiRoutes is the endpoint table derived from the file tree.\n")
	fmt.Fprintf(&b, "// Pass it to api.Register together with the application's api.Config.\n")
	fmt.Fprintf(&b, "func FsApiRoutes() []api.Route {\n\treturn []api.Route{\n")
	for _, e := range endpoints {
		ref := e.Var
		if e.Alias != "" {
			ref = e.Alias + "." + e.Var
		}
		fmt.Fprintf(&b, "\t\tapi.At(%q, %q, %s),\n", e.Method, e.Path, ref)
	}
	fmt.Fprintf(&b, "\t}\n}\n")
	return gofmt(b.Bytes())
}

// renderClient writes one method per endpoint over core/api's transport.
//
// The types are imported from the endpoint packages rather than redeclared:
// there is exactly one definition of a request or response shape in the
// program, and the client cannot drift from the handler because they are the
// same Go types.
func renderClient(endpoints []endpoint, pkg, apiPkg string) ([]byte, error) {
	imports := map[string]string{"api": apiPkg, "context": "context"}
	aliasFor := map[string]string{} // import path -> alias used in this file

	// Qualify a type argument for the client file: `PingQuery` means "in the
	// endpoint's own package", `telemetry.Event` means "wherever that file
	// imported telemetry from".
	qualify := func(e endpoint, expr string) string {
		expr = strings.TrimSpace(expr)
		if expr == "" || expr == "api.None" {
			return "api.None"
		}
		prefix := ""
		for strings.HasPrefix(expr, "*") || strings.HasPrefix(expr, "[]") {
			if strings.HasPrefix(expr, "*") {
				prefix, expr = prefix+"*", expr[1:]
			} else {
				prefix, expr = prefix+"[]", expr[2:]
			}
		}
		qual, name, qualified := strings.Cut(expr, ".")
		importPath := e.Import
		if qualified {
			p, ok := e.Imports[qual]
			if !ok {
				// The endpoint file used a qualifier it never imported, which
				// cannot compile — report it rather than emit a client that
				// fails to build for a reason two steps removed.
				panic(fmt.Sprintf("fsapis: %s refers to %s.%s but does not import %s", e.File, qual, name, qual))
			}
			importPath = p
		} else {
			name = expr
		}
		alias, ok := aliasFor[importPath]
		if !ok {
			alias = safeAlias(path.Base(importPath), aliasFor)
			aliasFor[importPath] = alias
			imports[alias] = importPath
		}
		return prefix + alias + "." + name
	}

	type method struct {
		Name, Doc, Signature, Body string
	}
	var methods []method
	for _, e := range endpoints {
		query := qualify(e, e.Query)
		body := qualify(e, e.Body)
		result := qualify(e, e.Result)

		args := []string{"ctx context.Context"}
		for _, p := range e.Params {
			args = append(args, goName(p, false)+" string")
		}
		queryArg, bodyArg := "nil", "nil"
		if query != "api.None" {
			args = append(args, "query "+query)
			queryArg = "query"
		}
		if body != "api.None" {
			args = append(args, "body "+body)
			bodyArg = "body"
		}

		pathExpr := fmt.Sprintf("%q", e.Path)
		if len(e.Params) > 0 {
			names := make([]string, 0, len(e.Params))
			for _, p := range e.Params {
				names = append(names, goName(p, false))
			}
			pathExpr = fmt.Sprintf("api.Path(%q, %s)", e.Path, strings.Join(names, ", "))
		}

		name := goName(e.Name, true)
		returns := "(" + result + ", error)"
		call := fmt.Sprintf("api.Call[%s](ctx, c.Transport, %q, %s, %s, %s)", result, e.Method, pathExpr, queryArg, bodyArg)
		bodySrc := "\treturn " + call + "\n"
		if result == "api.None" {
			returns = "error"
			bodySrc = "\t_, err := " + call + "\n\treturn err\n"
		}
		methods = append(methods, method{
			Name:      name,
			Doc:       fmt.Sprintf("// %s calls %s %s.", name, e.Method, e.Path),
			Signature: fmt.Sprintf("func (c *Client) %s(%s) %s {", name, strings.Join(args, ", "), returns),
			Body:      bodySrc,
		})
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by core/cmd/fsapis. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// A typed client over the same Go types the handlers are written against.\n")
	fmt.Fprintf(&b, "// Compiles for GOOS=js too, where net/http is the browser's fetch().\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import (\n")
	for _, alias := range sortedKeys(imports) {
		if alias == imports[alias] || alias == path.Base(imports[alias]) {
			fmt.Fprintf(&b, "\t%q\n", imports[alias])
			continue
		}
		fmt.Fprintf(&b, "\t%s %q\n", alias, imports[alias])
	}
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(&b, "// Client calls the API. An empty base URL means same origin, which is what\n")
	fmt.Fprintf(&b, "// a page running in the browser wants.\ntype Client struct{ *api.Transport }\n\n")
	fmt.Fprintf(&b, "func New(baseURL string) *Client { return &Client{Transport: api.NewTransport(baseURL)} }\n\n")

	sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
	for _, m := range methods {
		fmt.Fprintf(&b, "%s\n%s\n%s}\n\n", m.Doc, m.Signature, m.Body)
	}
	return gofmt(b.Bytes())
}

// gofmt formats the emitted source, and on failure shows it. A generator that
// cannot parse its own output must say what it produced, or the error is a line
// number in a file that was never written.
func gofmt(src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("%w\n\n%s", err, numbered(src))
	}
	return out, nil
}

func numbered(src []byte) string {
	var b strings.Builder
	for i, line := range strings.Split(string(src), "\n") {
		fmt.Fprintf(&b, "%4d | %s\n", i+1, line)
	}
	return b.String()
}

func safeAlias(base string, taken map[string]string) string {
	alias := strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return r
		}
		return '_'
	}, base)
	if alias == "" || unicode.IsDigit(rune(alias[0])) {
		alias = "p" + alias
	}
	used := map[string]bool{"api": true, "context": true}
	for _, a := range taken {
		used[a] = true
	}
	candidate := alias
	for i := 2; used[candidate]; i++ {
		candidate = fmt.Sprintf("%s%d", alias, i)
	}
	return candidate
}

// goName turns "Get Me" or "metric-series" into GetMe / metricSeries.
func goName(s string, exported bool) string {
	fields := strings.FieldsFunc(s, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var b strings.Builder
	for i, f := range fields {
		if i == 0 && !exported {
			b.WriteString(strings.ToLower(f[:1]) + f[1:])
			continue
		}
		b.WriteString(strings.ToUpper(f[:1]) + f[1:])
	}
	name := b.String()
	if name == "" {
		return "Endpoint"
	}
	return name
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
