// Code generated by tools/fsroutes. DO NOT EDIT.
// Source of truth is the directory tree under client/pages.

package pages

import (
	"github.com/mirairoad/howl-go/core/router"
)

// FsClientRoutes is the route table derived from the page tree.
func FsClientRoutes() []router.Route {
	return []router.Route{
		{Pattern: "/", Label: "Home", Page: Page, Head: Head, Mount: nil, Unmount: nil, Layouts: nil, Client: false, Raw: false},
	}
}
