// Code generated by core/cmd/mddocs. DO NOT EDIT.

package docs

// Entry is one documentation page.
type Entry struct{ Slug, Title, Blurb string }

// Index is every documentation page, in reading order.
var Index = []Entry{
	{Slug: "getting-started", Title: "Getting started", Blurb: "howl-go renders the same templ components on the server, into static files, and inside the browser via WebAssembly. One Go module, no Node, no npm, no client…"},
	{Slug: "routing", Title: "Routing", Blurb: "Routes come from the directory tree. core/cmd/fsroutes walks client/pages and generates a table that the HTTP mux, the layout chain, the static export and th…"},
	{Slug: "rendering", Title: "Rendering", Blurb: "A templ.Component is just Render(ctx, io.Writer). It cannot tell whether the writer is an HTTP response, a file, or a strings.Builder inside WebAssembly. Eve…"},
	{Slug: "lifecycle", Title: "Lifecycle", Blurb: "templ has no lifecycle and cannot have one: a component renders once to a writer and is finished. There is no mount, no effect, no re-render. So \"do somethin…"},
	{Slug: "reactivity", Title: "Reactivity", Blurb: "core/signal is fine-grained reactivity in the shape Vue's ref/computed/watch and Preact's signals popularised."},
	{Slug: "navigation", Title: "Navigation and prefetching", Blurb: "The client runtime (core/runtime/app.js, ~8 KB gzipped) intercepts same-origin links, swaps #outlet, and calls pushState. Any failure degrades to location.hr…"},
	{Slug: "constraints", Title: "Toolchain constraints", Blurb: "Several conventions from JavaScript frameworks cannot be ported to Go. These were verified, not assumed, and they explain why howl-go's naming looks the way …"},
}
