// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package todos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/mirairoad/howl-go/core/dom"
	"github.com/mirairoad/howl-go/core/signal"
	apiclient "github.com/mirairoad/howl-go/examples/toy_app/client/api"
	"github.com/mirairoad/howl-go/examples/toy_app/client/store"
	"github.com/mirairoad/howl-go/examples/toy_app/client/ui"
)

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"page\"><h1>The store runs in the browser</h1><p class=\"lede\">SSR'd from Go memory, then the same <code>store.Store</code> — compiled to wasm — takes over. Adds and deletes mutate locally and re-render locally; the server is told afterwards and never blocks you.</p><form class=\"todo-form\" method=\"post\" action=\"/api/todos\" data-todo-form><input name=\"text\" placeholder=\"add a todo…\" autocomplete=\"off\" required data-todo-input> <button type=\"submit\">Add</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Counter(store.TodosFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<ul class=\"todos\" id=\"todo-list\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.TodoList(store.TodosFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</ul><p class=\"hint\" id=\"todo-count\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d item(s) in server memory", len(store.TodosFrom(ctx))))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `client/pages/todos/index.templ`, Line: 33, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p><!-- The snapshot this page was rendered from, serialised for the\n\t\t     browser store. Mount restores it: the store starts with exactly\n\t\t     what is on screen, and no request is made to get there. -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.JSONScript("todos", store.SnapshotFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ---------------------------------------------------------------------------
// This page has no JavaScript island. Mount hydrates the browser store from
// the document, renders with the same templ component the server uses, and
// wires the handlers — all in Go.
//
// Mount runs inside a scope. Every listener, effect and watcher registered here
// is released when the page is swapped out, so there is no release slice, no
// stop func to keep, and no Unmount — the runtime does the bookkeeping the page
// used to. Unmount still exists for teardown that is not a registration: a
// timer to cancel, a draft to save.
// ---------------------------------------------------------------------------

func Mount() {
	root := dom.Root()

	// Hydrate from the document, not from a fetch. The server serialised the
	// snapshot it rendered from into this fragment, so the browser store
	// starts with exactly what the user is looking at: no request, no
	// empty-then-full flash, and it works on a cold load and after a
	// client-side navigation alike. Restore publishes to the signal; the
	// effect below then renders from it on its first run.
	var sn store.Snapshot
	if err := dom.Embedded("todos", &sn); err != nil {
		dom.Warn("[todos] no embedded snapshot:", err.Error())
	} else {
		store.Client().Restore(sn)
		dom.Log("[todos] hydrated from the document,", len(sn.Items), "items")
	}

	// One delegated listener per action, on the page root. A delegated listener
	// matches descendants that exist now and descendants a later repaint
	// renders, so the delete buttons are covered without ever rebinding — and
	// there is one js.Func per action for the life of the page, not one per row
	// per repaint.
	root.Delegate("click", "[data-add]", func(dom.Event) {
		mutate(store.Op{Kind: "add", Text: "added from a Go click handler"})
	})
	root.Delegate("click", "[data-del]", func(e dom.Event) {
		if n, err := strconv.Atoi(e.Target().Attr("data-del")); err == nil {
			mutate(store.Op{Kind: "del", ID: n})
		}
	})
	// submit is prevented before the handler runs: the form would otherwise
	// post to /api/todos and reload the document.
	root.Query("[data-todo-form]").On("submit", func(e dom.Event) {
		input := e.Target().Query("[data-todo-input]")
		text := strings.TrimSpace(input.Value())
		if text == "" {
			return
		}
		mutate(store.Op{Kind: "add", Text: text})
		input.SetValue("")
	})

	// repaint reads store.Todos inside itself, so the effect discovers that
	// dependency by running — there is no list of values to declare. This is the
	// difference from useEffect(fn, [deps]): reads here are observable, so the
	// dependency list cannot be wrong.
	signal.Effect(repaint)

	// A watcher on one derived value. Fires only on a transition, with both
	// values — and not on the initial run.
	signal.Watch(store.TodoCount.Get, func(now, before int) {
		dom.Log("[todos] count changed", before, "->", now)
	})

	dom.Log("[todos] mounted")
}

// mutate applies an op locally for an instant repaint, then tells the server.
// The user never waits on the round-trip, and this is the only request the
// page makes.
func mutate(op store.Op) {
	store.Client().Apply(op)
	go func() {
		if _, err := apiclient.New("").SyncTodos(context.Background(), []store.Op{op}); err != nil {
			dom.Warn("[todos] sync deferred:", err.Error())
		}
	}()
}

// repaint is the whole "update the screen": read through the signal — that is
// what registers this effect as a dependent — and render the same templ
// component the server used into the same element. Render on an element the
// navigation has already thrown away is a no-op, which is how an effect ends.
func repaint() {
	root := dom.Root()
	items := store.Todos.Get()
	if err := root.Query("#todo-list").Render(ui.TodoList(items)); err != nil {
		dom.Warn("[todos] render failed:", err.Error())
		return
	}
	root.Query("[data-todo-count]").SetText(countText(len(items)))
	root.Query("[data-watchers]").SetText("computed count: " + itoa(store.TodoCount.Get()))
}

var _ = templruntime.GeneratedTemplate
