// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package todos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/mirairoad/howl-go/core/dom"
	"github.com/mirairoad/howl-go/core/signal"
	apiclient "github.com/mirairoad/howl-go/examples/toy_app/client/api"
	"github.com/mirairoad/howl-go/examples/toy_app/client/store"
	"github.com/mirairoad/howl-go/examples/toy_app/client/ui"
)

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"page\"><h1>The store runs in the browser</h1><p class=\"lede\">SSR'd from Go memory, then the same <code>store.Store</code> — compiled to wasm — takes over. Adds and deletes mutate locally and re-render locally; the server is told afterwards and never blocks you.</p><form class=\"todo-form\" method=\"post\" action=\"/api/todos\" data-todo-form><input name=\"text\" placeholder=\"add a todo…\" autocomplete=\"off\" required data-todo-input> <button type=\"submit\">Add</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Counter(store.TodosFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<ul class=\"todos\" id=\"todo-list\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.TodoList(store.TodosFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</ul><p class=\"hint\" id=\"todo-count\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d item(s) in server memory", len(store.TodosFrom(ctx))))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `client/pages/todos/index.templ`, Line: 33, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ---------------------------------------------------------------------------
// This page has no JavaScript island. Mount hydrates the browser store, renders
// with the same templ component the server uses, and wires the handlers — all
// in Go. Unmount releases the subscription, which is the entire reason it
// exists: a subscription that outlives its DOM keeps firing against nodes that
// were thrown away, and every visit adds another one.
// ---------------------------------------------------------------------------

// release holds everything Mount registered; rows holds the per-row listeners,
// which are re-bound on every repaint and so are released separately. Both are
// func() — a signal's stop func and a listener's release func are the same
// shape, which is what lets Unmount treat them alike.
var release, rows []func()

func Mount() {
	root := dom.Root()

	// Any handler can reach the browser's store directly — it is a
	// package-level instance, not something threaded through a component tree.
	release = append(release, root.Query("[data-add]").On("click", func() {
		mutate(store.Op{Kind: "add", Text: "added from a Go click handler"})
	}))
	release = append(release, root.Query("[data-todo-form]").On("submit", func() {
		text := strings.TrimSpace(root.Query("[data-todo-input]").Value())
		if text == "" {
			return
		}
		mutate(store.Op{Kind: "add", Text: text})
		root.Query("[data-todo-input]").SetValue("")
	}))

	// repaint reads store.Todos inside itself, so the effect discovers that
	// dependency by running — there is no list of values to declare. This is the
	// difference from useEffect(fn, [deps]): reads here are observable, so the
	// dependency list cannot be wrong.
	release = append(release, signal.Effect(repaint))

	// A watcher on one derived value. Fires only on a transition, with both
	// values — and not on the initial run.
	release = append(release, signal.Watch(store.TodoCount.Get, func(now, before int) {
		dom.Log("[todos] count changed", before, "->", now)
	}))

	// Hydrate from the server, then render from the local store.
	go func() {
		sn, err := apiclient.New("").Todos(context.Background())
		if err != nil {
			dom.Warn("[todos] hydrate failed:", err.Error())
			return
		}
		store.Client().Restore(sn) // publishes to the signal, which repaints
		dom.Log("[todos] hydrated", len(sn.Items), "items")
	}()

	dom.Log("[todos] mounted")
}

func Unmount() {
	// Every registration made in Mount is released here — effects, watchers and
	// DOM listeners alike. An effect that outlives its DOM keeps firing against
	// nodes that were thrown away, and a listener's js.Func stays alive on the
	// JS side until it is released, so both leak once per visit otherwise.
	dom.Off(rows...)
	dom.Off(release...)
	rows, release = nil, nil
	dom.Log("[todos] unmounted")
}

// mutate applies an op locally for an instant repaint, then tells the server.
// The user never waits on the round-trip.
func mutate(op store.Op) {
	store.Client().Apply(op)
	go func() {
		if _, err := apiclient.New("").SyncTodos(context.Background(), []store.Op{op}); err != nil {
			dom.Warn("[todos] sync deferred:", err.Error())
		}
	}()
}

func repaint() {
	root := dom.Root()
	if !root.Query("#todo-list").Valid() {
		return // page already swapped away
	}
	// Read through the signal, not the store: that is what registers this
	// effect as a dependent.
	items := store.Todos.Get()

	var sb strings.Builder
	if err := ui.TodoList(items).Render(context.Background(), &sb); err != nil {
		dom.Warn("[todos] render failed:", err.Error())
		return
	}
	// Rendered by the same templ component the server uses, inside the browser.
	root.Query("#todo-list").SetHTML(sb.String())
	root.Query("[data-todo-count]").SetText(countText(len(items)))
	root.Query("[data-watchers]").SetText("computed count: " + itoa(store.TodoCount.Get()))

	// Delete buttons are re-created on every repaint, so rebind each time —
	// and release the previous batch first. SetHTML threw those elements away,
	// but a js.Func is held alive from the JS side until it is released, so
	// skipping this leaks one closure per row per repaint for the life of the
	// tab. It is the one leak that grows while the user simply uses the page.
	dom.Off(rows...)
	rows = rows[:0]
	for _, btn := range root.QueryAll("[data-del]") {
		id := btn.Attr("data-del")
		rows = append(rows, btn.On("click", func() {
			n, err := strconv.Atoi(id)
			if err == nil {
				mutate(store.Op{Kind: "del", ID: n})
			}
		}))
	}
}

var _ = templruntime.GeneratedTemplate
