// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package todos

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"github.com/mirairoad/howl-go/core/dom"
	"github.com/mirairoad/howl-go/core/signal"
	"github.com/mirairoad/howl-go/examples/toy_app/client/store"
	"github.com/mirairoad/howl-go/examples/toy_app/client/ui"
)

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"page\"><h1>The store runs in the browser</h1><p class=\"lede\">SSR'd from Go memory, then the same <code>store.Store</code> — compiled to wasm — takes over. Adds and deletes mutate locally and re-render locally; the server is told afterwards and never blocks you.</p><form class=\"todo-form\" method=\"post\" action=\"/api/todos\" data-todo-form><input name=\"text\" placeholder=\"add a todo…\" autocomplete=\"off\" required data-todo-input> <button type=\"submit\">Add</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Counter(store.TodosFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<ul class=\"todos\" id=\"todo-list\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.TodoList(store.TodosFrom(ctx)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</ul><p class=\"hint\" id=\"todo-count\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d item(s) in server memory", len(store.TodosFrom(ctx))))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `client/pages/todos/index.templ`, Line: 35, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ---------------------------------------------------------------------------
// This page has no JavaScript island. Mount hydrates the browser store, renders
// with the same templ component the server uses, and wires the handlers — all
// in Go. Unmount releases the subscription, which is the entire reason it
// exists: a subscription that outlives its DOM keeps firing against nodes that
// were thrown away, and every visit adds another one.
// ---------------------------------------------------------------------------

var stopEffect, stopWatch func()

func Mount() {
	root := dom.Root()

	// Any handler can reach the browser's store directly — it is a
	// package-level instance, not something threaded through a component tree.
	root.Query("[data-add]").On("click", func() {
		mutate(store.Op{Kind: "add", Text: "added from a Go click handler"})
	})
	root.Query("[data-todo-form]").On("submit", func() {
		text := strings.TrimSpace(root.Query("[data-todo-input]").Value())
		if text == "" {
			return
		}
		mutate(store.Op{Kind: "add", Text: text})
		root.Query("[data-todo-input]").SetValue("")
	})

	// repaint reads store.Todos inside itself, so the effect discovers that
	// dependency by running — there is no list of values to declare. This is the
	// difference from useEffect(fn, [deps]): reads here are observable, so the
	// dependency list cannot be wrong.
	stopEffect = signal.Effect(repaint)

	// A watcher on one derived value. Fires only on a transition, with both
	// values — and not on the initial run.
	stopWatch = signal.Watch(store.TodoCount.Get, func(now, before int) {
		dom.Log("[todos] count changed", before, "->", now)
	})

	// Hydrate from the server, then render from the local store.
	go func() {
		res, err := http.Get("/api/todos")
		if err != nil {
			dom.Warn("[todos] hydrate failed:", err.Error())
			return
		}
		defer res.Body.Close()
		var sn store.Snapshot
		if err := json.NewDecoder(res.Body).Decode(&sn); err != nil {
			dom.Warn("[todos] decode failed:", err.Error())
			return
		}
		store.Client().Restore(sn) // publishes to the signal, which repaints
		dom.Log("[todos] hydrated", len(sn.Items), "items")
	}()

	dom.Log("[todos] mounted")
}

func Unmount() {
	// Every reactive registration made in Mount is released here. An effect that
	// outlives its DOM keeps firing against nodes that were thrown away.
	for _, stop := range []func(){stopEffect, stopWatch} {
		if stop != nil {
			stop()
		}
	}
	stopEffect, stopWatch = nil, nil
	dom.Log("[todos] unmounted")
}

// mutate applies an op locally for an instant repaint, then tells the server.
// The user never waits on the round-trip.
func mutate(op store.Op) {
	store.Client().Apply(op)
	go func() {
		body, _ := json.Marshal([]store.Op{op})
		res, err := http.Post("/api/todos/sync", "application/json", bytes.NewReader(body))
		if err != nil {
			dom.Warn("[todos] sync deferred:", err.Error())
			return
		}
		res.Body.Close()
	}()
}

func repaint() {
	root := dom.Root()
	if !root.Query("#todo-list").Valid() {
		return // page already swapped away
	}
	// Read through the signal, not the store: that is what registers this
	// effect as a dependent.
	items := store.Todos.Get()

	var sb strings.Builder
	if err := ui.TodoList(items).Render(context.Background(), &sb); err != nil {
		dom.Warn("[todos] render failed:", err.Error())
		return
	}
	// Rendered by the same templ component the server uses, inside the browser.
	root.Query("#todo-list").SetHTML(sb.String())
	root.Query("[data-todo-count]").SetText(countText(len(items)))
	root.Query("[data-watchers]").SetText("computed count: " + itoa(store.TodoCount.Get()))

	// Delete buttons are re-created on every repaint, so rebind each time.
	for _, btn := range root.QueryAll("[data-del]") {
		id := btn.Attr("data-del")
		btn.On("click", func() {
			n, err := strconv.Atoi(id)
			if err == nil {
				mutate(store.Op{Kind: "del", ID: n})
			}
		})
	}
}

var _ = templruntime.GeneratedTemplate
