// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// Code generated by core/cmd/mddocs from the Markdown source. DO NOT EDIT.

package getting_started

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Head() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<title>Getting started — howl-go</title><meta name=\"description\" content=\"howl-go renders the same templ components on the server, into static files, and inside the browser via WebAssembly. One Go module, no Node, no npm, no client…\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<article class=\"prose\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(body).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

const body = "<h1>Getting started</h1>\n<p>howl-go renders the same templ components on the server, into static files, and inside the browser via WebAssembly. One Go module, no Node, no npm, no client framework.</p>\n<h2>Install</h2>\n<pre><code class=\"language-bash\">go get github.com/mirairoad/howl-go\n</code></pre>\n<h2>The smallest app</h2>\n<p>Three files: a document shell, a page, and a <code>main.go</code>.</p>\n<pre><code>client/pages/app.templ     the document shell — reserved, never a route\nclient/pages/index.templ   /\nmain.go\n</code></pre>\n<p><code>client/pages/index.templ</code>:</p>\n<pre><code class=\"language-templ\">package pages\n\ntempl Page() {\n\t&lt;h1&gt;Hello&lt;/h1&gt;\n}\n</code></pre>\n<p><code>main.go</code>:</p>\n<pre><code class=\"language-go\">a := app.New(app.Config{\n\tRoutes: pages.FsClientRoutes(),\n\tShell:  pages.App,\n\tPublic: public,\n})\nlog.Fatal(a.Listen(a.Mux()))\n</code></pre>\n<p><code>FsClientRoutes()</code> is generated by walking the page directory — you never register a route by hand.</p>\n<h2>Build</h2>\n<pre><code class=\"language-bash\">go run github.com/mirairoad/howl-go/core/cmd/fsroutes -module your.module/client/pages\ngo tool templ generate\ngo build .\n</code></pre>\n<p>The example apps wrap this in a <code>Makefile</code>; <code>make</code> runs all three steps.</p>\n<h2>What you get</h2>\n<table>\n<thead>\n<tr>\n<th></th>\n<th></th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>first paint</td>\n<td>server-rendered HTML, crawlable</td>\n</tr>\n<tr>\n<td>navigation</td>\n<td>client-side, prefetched on intent</td>\n</tr>\n<tr>\n<td>a route marked <code>.client</code></td>\n<td>rendered in the browser, zero bytes over the wire</td>\n</tr>\n<tr>\n<td><code>make static</code></td>\n<td>every static route written to disk</td>\n</tr>\n</tbody>\n</table>\n"

var _ = templruntime.GeneratedTemplate
