// Command mddocs turns a directory of Markdown files into templ pages.
//
//	www/docs/routing.md  ->  www/client/pages/docs/routing/index.templ  ->  /docs/routing
//
// Rendering happens at build time, so Markdown never reaches a running binary:
// goldmark is a dependency of this tool only, not of the server or the wasm
// bundle. The generated pages are ordinary routes, which means they are
// crawlable, statically exportable and prefetchable like any other.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

type doc struct {
	Slug  string
	Pkg   string
	Title string
	Blurb string
	HTML  string
	Order int
}

var (
	h1Re = regexp.MustCompile(`(?m)^#\s+(.+?)\s*$`)
	// Stripped from a blurb, once per document rather than once per line.
	markupRe = regexp.MustCompile("[`*]")
	orderRe  = regexp.MustCompile(`^(\d+)[-_]`)
	paraRe   = regexp.MustCompile(`(?m)^([A-Za-z\x60*\[].+)$`)
)

func main() {
	var in, outDir, indexPkg string
	flag.StringVar(&in, "in", "docs", "directory of .md files")
	flag.StringVar(&outDir, "out", "client/pages/docs", "directory to write templ pages into")
	flag.StringVar(&indexPkg, "index-pkg", "docs", "package name for the generated index page")
	flag.Parse()

	entries, err := os.ReadDir(in)
	if err != nil {
		log.Fatal(err)
	}

	md := goldmark.New(goldmark.WithExtensions(extension.GFM, extension.Table))

	var docs []doc
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".md" {
			continue
		}
		src, err := os.ReadFile(filepath.Join(in, e.Name()))
		if err != nil {
			log.Fatal(err)
		}
		var buf bytes.Buffer
		if err := md.Convert(src, &buf); err != nil {
			log.Fatal(err)
		}

		name := strings.TrimSuffix(e.Name(), ".md")
		d := doc{
			Slug:  slug(name),
			Title: title(string(src), name),
			Blurb: blurb(string(src)),
			HTML:  buf.String(),
			Order: order(name),
		}
		d.Pkg = pkgName(d.Slug)
		docs = append(docs, d)
	}
	sort.Slice(docs, func(i, j int) bool {
		if docs[i].Order != docs[j].Order {
			return docs[i].Order < docs[j].Order
		}
		return docs[i].Slug < docs[j].Slug
	})

	for _, d := range docs {
		dir := filepath.Join(outDir, d.Slug)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			log.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, "index.templ"), page(d), 0o644); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("  /docs/%-18s %s\n", d.Slug, filepath.Join(dir, "index.templ"))
	}

	if err := os.WriteFile(filepath.Join(outDir, "index.templ"), index(docs, indexPkg), 0o644); err != nil {
		log.Fatal(err)
	}
	src, err := format.Source(manifest(docs, indexPkg))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(outDir, "docs_gen.go"), src, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%d docs -> %s\n", len(docs), outDir)
}

// page writes one documentation route. The HTML is emitted as a quoted Go
// string rather than a raw literal, because Markdown routinely contains
// backticks and a raw literal cannot escape them.
func page(d doc) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by core/cmd/mddocs from the Markdown source. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", d.Pkg)
	fmt.Fprintf(&b, "templ Head() {\n\t<title>%s — howl-go</title>\n", esc(d.Title))
	if d.Blurb != "" {
		fmt.Fprintf(&b, "\t<meta name=\"description\" content=\"%s\"/>\n", esc(d.Blurb))
	}
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "templ Page() {\n\t<article class=\"prose\">\n\t\t@templ.Raw(body)\n\t</article>\n}\n\n")
	fmt.Fprintf(&b, "const body = %s\n", strconv.Quote(d.HTML))
	return b.Bytes()
}

func index(docs []doc, pkg string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by core/cmd/mddocs. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "templ Head() {\n\t<title>Documentation — howl-go</title>\n}\n\n")
	fmt.Fprintf(&b, "templ Page() {\n")
	fmt.Fprintf(&b, "\t<article class=\"prose\">\n\t\t<h1>Documentation</h1>\n\t\t<ul class=\"toc\">\n")
	fmt.Fprintf(&b, "\t\t\tfor _, d := range Index {\n")
	fmt.Fprintf(&b, "\t\t\t\t<li>\n\t\t\t\t\t<a href={ templ.SafeURL(\"/docs/\" + d.Slug) }>{ d.Title }</a>\n")
	fmt.Fprintf(&b, "\t\t\t\t\tif d.Blurb != \"\" {\n\t\t\t\t\t\t<p>{ d.Blurb }</p>\n\t\t\t\t\t}\n\t\t\t\t</li>\n")
	fmt.Fprintf(&b, "\t\t\t}\n\t\t</ul>\n\t</article>\n}\n")
	return b.Bytes()
}

// manifest is the table of contents, usable by any page (the index, a sidebar,
// a "next page" link) without re-reading the Markdown.
func manifest(docs []doc, pkg string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by core/cmd/mddocs. DO NOT EDIT.\n\npackage %s\n\n", pkg)
	fmt.Fprintf(&b, "// Entry is one documentation page.\ntype Entry struct{ Slug, Title, Blurb string }\n\n")
	fmt.Fprintf(&b, "// Index is every documentation page, in reading order.\nvar Index = []Entry{\n")
	for _, d := range docs {
		fmt.Fprintf(&b, "\t{Slug: %q, Title: %q, Blurb: %q},\n", d.Slug, d.Title, d.Blurb)
	}
	fmt.Fprintf(&b, "}\n")
	return b.Bytes()
}

func esc(s string) string {
	return strings.NewReplacer(`&`, "&amp;", `<`, "&lt;", `>`, "&gt;", `"`, "&quot;").Replace(s)
}

// slug strips a leading sort prefix: 02-routing.md -> routing.
func slug(name string) string { return orderRe.ReplaceAllString(name, "") }

func order(name string) int {
	if m := orderRe.FindStringSubmatch(name); m != nil {
		n, _ := strconv.Atoi(m[1])
		return n
	}
	return 1 << 30
}

// pkgName turns a slug into a legal Go package identifier — hyphens are fine in
// a directory name and an import path, but not in a package clause.
func pkgName(s string) string {
	s = strings.NewReplacer("-", "_", ".", "_").Replace(s)
	if s == "" || (s[0] >= '0' && s[0] <= '9') {
		s = "d" + s
	}
	return s
}

func title(src, fallback string) string {
	if m := h1Re.FindStringSubmatch(src); m != nil {
		return strings.TrimSpace(m[1])
	}
	return strings.ReplaceAll(slug(fallback), "-", " ")
}

// blurb is the first prose paragraph after the title, used for the index and
// the page's meta description.
func blurb(src string) string {
	body := src
	if m := h1Re.FindStringIndex(src); m != nil {
		body = src[m[1]:]
	}
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "```") {
			continue
		}
		if paraRe.MatchString(line) {
			line = markupRe.ReplaceAllString(line, "")
			if len(line) > 160 {
				line = line[:157] + "…"
			}
			return line
		}
	}
	return ""
}
