// Code generated by core/cmd/fsapis. DO NOT EDIT.
// Source of truth is the directory tree under server/apis.

package apis

import (
	"github.com/mirairoad/howl-go/core/api"
	e0 "github.com/mirairoad/howl-go/examples/toy_app/server/apis/todos"
)

// FsApiRoutes is the endpoint table derived from the file tree.
// Pass it to api.Register together with the application's api.Config.
func FsApiRoutes() []api.Route {
	return []api.Route{
		api.At("GET", "/api/metrics", Metrics),
		api.At("GET", "/api/todos", e0.List),
		api.At("POST", "/api/todos/sync", e0.Sync),
	}
}
