// Code generated by core/cmd/fsapis. DO NOT EDIT.
//
// A typed client over the same Go types the handlers are written against.
// Compiles for GOOS=js too, where net/http is the browser's fetch().

package apiclient

import (
	"context"
	"github.com/mirairoad/howl-go/core/api"
	"github.com/mirairoad/howl-go/examples/toy_app/client/store"
)

// Client calls the API. An empty base URL means same origin, which is what
// a page running in the browser wants.
type Client struct{ *api.Transport }

func New(baseURL string) *Client { return &Client{Transport: api.NewTransport(baseURL)} }

// Metrics calls GET /api/metrics.
func (c *Client) Metrics(ctx context.Context) (store.Metrics, error) {
	return api.Call[store.Metrics](ctx, c.Transport, "GET", "/api/metrics", nil, nil)
}

// SyncTodos calls POST /api/todos/sync.
func (c *Client) SyncTodos(ctx context.Context, body []store.Op) (store.Snapshot, error) {
	return api.Call[store.Snapshot](ctx, c.Transport, "POST", "/api/todos/sync", nil, body)
}

// Todos calls GET /api/todos.
func (c *Client) Todos(ctx context.Context) (store.Snapshot, error) {
	return api.Call[store.Snapshot](ctx, c.Transport, "GET", "/api/todos", nil, nil)
}
